div.fbisCarousel{width:440px;height:150px;overflow:hidden;display:block;position:relative;float:left;clear:both}
div.fbisCarousel ul{float:left;margin:0;padding:0;list-style:none;position:relative;width:2000px;} /* Container that scrolls inside the parent div */
div.fbisCarousel ul li{display:block;float:left;overflow:hidden;border:solid 1px #eee;padding:10px;margin:0}
div.fbisCarousel ul li div{background:transparent url(../images/slidey.png) no-repeat top right}

div.fbisCarousel .arrows {width:400px;float:left;}
div.fbisCarousel .arrows a{width:30px;display:block;padding:4px 0;height:30px}
div.fbisCarousel .arrows a span{display:none;}
div.fbisCarousel .arrows a.slideleft {background:transparent url(images/fbisCarouselArrows.png) no-repeat center left;float:left}
div.fbisCarousel .arrows a.slideright {background:transparent url(images/fbisCarouselArrows.png) no-repeat center right;float:right;}